services:
  #Postgres-DB
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
  #Radis-DB
    redis:
        image: 'redis:latest'
        command: ["redis-server", "--protected-mode", "no"]
  #Api
    api:
        build:
            context: ./server
        image: "docker.io/priyac579/complex-api"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #worker
    worker:
      build: ./worker
      image: "docker.io/priyac579/complex-worker"
      environment:
         - REDIS_HOST=redis
         - REDIS_PORT=6379
    #Client
    client:
      build: ./client
      image: "docker.io/priyac579/complex-client"
    #Nginx
    nginx:
      depends_on:
           - api
           - client
      restart: always
      build: ./nginx
      ports:
            - '8082:80'